name: JS - Lint and test

on:
  push:
    branches:
      - develop
      - master
    tags:
      - uat-*
  pull_request:
    branches:
      - develop
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages using yarn
        run: yarn install

      - name: Lint using ESLint
        run: yarn lint .

      - name: Run tests using Jest
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
